# permissions for end users to view nodehealthchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodehealthcheck-viewer-role
rules:
- apiGroups:
  - remediation.medik8s.io
  resources:
  - nodehealthchecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - remediation.medik8s.io
  resources:
  - nodehealthchecks/status
  verbs:
  - get
