# permissions for end users to edit nodehealthchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodehealthcheck-editor-role
rules:
- apiGroups:
  - remediation.medik8s.io
  resources:
  - nodehealthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - remediation.medik8s.io
  resources:
  - nodehealthchecks/status
  verbs:
  - get
