
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - remediation.medik8s.io
  resources:
  - nodehealthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - remediation.medik8s.io
  resources:
  - nodehealthchecks/finalizers
  verbs:
  - update
- apiGroups:
  - remediation.medik8s.io
  resources:
  - nodehealthchecks/status
  verbs:
  - get
  - patch
  - update
