---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machine.openshift.io
  resources:
  - machinehealthchecks
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.openshift.io
  resources:
  - machinehealthchecks/finalizers
  verbs:
  - update
- apiGroups:
  - machine.openshift.io
  resources:
  - machinehealthchecks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - '*'
- apiGroups:
  - remediation.medik8s.io
  resources:
  - nodehealthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - remediation.medik8s.io
  resources:
  - nodehealthchecks/finalizers
  verbs:
  - update
- apiGroups:
  - remediation.medik8s.io
  resources:
  - nodehealthchecks/status
  verbs:
  - get
  - patch
  - update
