apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: node-healthcheck-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NodeHealthCheck is the Schema for the nodehealthchecks API
      displayName: Node Health Check
      kind: NodeHealthCheck
      name: nodehealthchecks.remediation.medik8s.io
      resources:
      - kind: Nodes
        name: ""
        version: v1
      specDescriptors:
      - description: Any farther remediation is only allowed if at most "MaxUnhealthy"
          nodes selected by "selector" are not healthy. Expects either a positive
          integer value or a percentage value. Percentage values must be positive
          whole numbers and are capped at 100%. Both 0 and 0% are valid and will block
          all remediation.
        displayName: Max Unhealthy
        path: maxUnhealthy
      - description: "RemediationTemplate is a reference to a remediation template
          provided by an infrastructure provider. \n If a node needs remediation the
          controller will create an object from this template and then it should be
          picked up by a remediation provider."
        displayName: Remediation Template
        path: remediationTemplate
      - description: 'Label selector to match nodes whose health will be exercised.
          Note: An empty selector will match all nodes.'
        displayName: Selector
        path: selector
      - description: UnhealthyConditions contains a list of the conditions that determine
          whether a node is considered unhealthy.  The conditions are combined in
          a logical OR, i.e. if any of the conditions is met, the node is unhealthy.
        displayName: Unhealthy Conditions
        path: unhealthyConditions
      statusDescriptors:
      - description: HealthyNodes specified the number of healthy nodes observed
        displayName: healthynodes
        path: healthyNodes
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podStatuses
      - description: InFlightRemediations records the timestamp when remediation triggered
          per node
        displayName: inFlightRemediations
        path: inFlightRemediations
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podStatuses
      - description: ObservedNodes specified the number of nodes observed by using
          the NHC spec.selecor
        displayName: observedNodes
        path: observedNodes
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podStatuses
      version: v1alpha1
  description: This operator deploys the Node Health Check controller and its artifacts
  displayName: Node Health Check Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Remediation
  - Fencing
  - medik8s
  - k8s
  links:
  - name: Node Healthcheck Operator
    url: https://node-healthcheck-operator.domain
  maturity: alpha
  provider:
    name: medik8s.io
    url: https://github.com/medik8s
  version: 0.0.0
