apiVersion: remediation.medik8s.io/v1alpha1
kind: NodeHealthCheck
metadata:
  name: nodehealthcheck-sample
  namespace: openshift-operators
spec:
#  optional
  selector:
    matchExpressions:
      - key: node-role.kubernetes.io/worker
        operator: Exists
#    matchLabels:
#      kubernetes.io/os: linux
#    optionally use more fine grained matching
#    matchExpressions:
#      - key: another-node-label-key
#        operator: In
#        values:
#          - another-node-label-value

  minHealthy: "51%"
  unhealthyConditions:
    - type: Ready
      status: "False"
      duration: 300s
    - type: Ready
      status: Unknown
      duration: 300s
  remediationTemplate:
    kind: PoisonPillRemediationTemplate
    apiVersion: poison-pill.medik8s.io/v1alpha1
    name: poison-pill-default-template
    namespace: openshift-operators
